server:
  port: 8902

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8671/eureka/,http://eureka2:8672/eureka/,http://eureka3:8673/eureka/
rheakv:
  instance:
    port: 10003
    dbPath: rhea_db/
    dataPath: raft_data/
  cluster:
    name: cloudin-executor
    nodes: 127.0.0.1:10002,127.0.0.1:10003