server:
  port: 8901
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18671/eureka/,http://localhost:18672/eureka/
rheakv:
  instance:
    port: 10001
    dbPath: rhea_db/
    dataPath: raft_data/
  cluster:
    name: cloudin-executor
    nodes: 127.0.0.1:10001
pipeline:
  status: false