server:
  port: 8801
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
election:
  dataPath: /Users/chengyajie/data/dev
  groupId: cloudin_arrange
  serverIdStr: 127.0.0.1:9761
  initialConfStr: 127.0.0.1:9761